version: "3.3"
networks:
  docker.localhost:
    driver: bridge
services:
  site:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - docker.localhost

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - docker.localhost

  php:
    build:
      context: "./docker/php"
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/etc/conf.d:/usr/local/etc/php/conf.d:delegated
    ports:
      - "9000:9000"
    networks:
      - docker.localhost


  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - docker.localhost
  npm:
    image: node:14.8
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
  artisan:
    build:
      context: "./docker/php"
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - docker.localhost
